### ISSUE TITLE
Publish on rubygems

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-post-order-plugin#2]
Hi @owen2345.

It's possible publish this gem in RubyGems?

Thanks!

**Comment by owen2345** [comment]
yes it is!

**Comment by raulanatol** [comment]
Exists a problem because the name of the gem is not the same:
- gem "camaleon_post_order"
- https://rubygems.org/gems/post_reorder
- https://github.com/owen2345/camaleon-post-order-plugin/blob/master/camaleon_post_order.gemspec#L8

**Comment by raulanatol** [comment]
@owen2345 if you want I can publish the gem and change the owner to you.

**Comment by owen2345** [comment]
Hi Raul,  please do it! I am too busy with a personal problem..

**Comment by raulanatol** [comment]
Done!
https://rubygems.org/gems/camaleon_post_order
